{
 "title": "Fruits Catalog Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Invocations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Fruits API invocations",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{exception=\"None\",method=\"GET\",outcome=\"SUCCESS\",status=\"200\",uri=\"/api/fruits\",}"
    }
   ]
  },
  { "title": "Response Times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Fruits API - Response Times",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_sum{exception=\"None\",method=\"GET\",outcome=\"SUCCESS\",status=\"200\",uri=\"/api/fruits\",} / http_server_requests_seconds_count{exception=\"None\",method=\"GET\",outcome=\"SUCCESS\",status=\"200\",uri=\"/api/fruits\",}",
     "legendFormat": "Mean response time"
    }
   ]
  },
  { "title": "JVM insights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Backend JVM",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{endpoint=\"8080-tcp\", area=\"heap\"}",
     "legendFormat": "{{id}}"
    }
   ]
  }
 ]
}